### ISSUE TITLE
Non removed existing plists license with option "--no-clean" not added in acknowledgements plist

### ISSUE THREAD

**Issue by martias** [Building42/AckAck#3]
When using the option `--no-clean` to not remove manually generated .plist files from Licences folder and running the scripts, the plist are not erased but they are also not added to the acknowledgements.plist file

I fixed it in version 2 by looking for .plist files in the Licences folder after `create_license_plist`

```python
for root, dirs, files in os.walk(plists_path):
    for file in files:
        file_name = os.path.splitext(file)[0]
        frameworks.append(file_name)
```

**Comment by yvbeek** [comment]
Great idea and thanks for the code snippet. I've worked it into a new version (4.1 RC).

For example `SomeFramework` is a plist I created by hand:
```
$ ./ackack.py --no-clean
Input folder(s): /Users/Yvo/Projects/Test/Carthage/Checkouts
Output folder: /Users/Yvo/Projects/Test/Resources/Config/Settings.bundle
Searching licenses...
Creating license plist for Charts
Updating license plist for CocoaAsyncSocket
Updating license plist for HTTPParserC
Tracking license plist for SomeFramework
Updating license plist for SwiftyJSON
Updating license plist for Telegraph
Updating license plist for Zip
Updating acknowledgements plist
```

As you can see logging has been updated a bit too:
- "Creating" for licenses that don't have a plist yet
- "Updating" for licenses that already have a plist
- "Tracking" for existing plists that don't have a license

Let me know if it works for you!

**Comment by martias** [comment]
Thanks @Zyphrax for the fast reply to this issue. I do not have access to 4.1 RC, but as you describe it, it would solve the issue. The change in the logging also makes it more clear when creating/updating and aggregating manually generated plist licences.
Thanks for sharing your work! 🥇

**Comment by yvbeek** [comment]
@martias The latest script on the master branch is the 4.1 RC version.
You can download it here: [ackack.py](https://raw.githubusercontent.com/Building42/AckAck/master/ackack.py)

In terminal you can do the following:
```bash
wget https://raw.githubusercontent.com/Building42/AckAck/master/ackack.py
chmod +x ackack.py
```

Please give it a spin and let me know if you run into any issues with it!

**Comment by martias** [comment]
Thank you very much for the quick response. I have tested the script and it works as expected. You can close this issue 👍
