### ISSUE TITLE
On iPadOS13.1 back to acknowledgements from license detail page crashes

### ISSUE THREAD

**Issue by sashahcat** [Building42/AckAck#4]
This is of course an Apple bug but reporting to see about a work around until Apple fixes their end. Hitting the back button from a settings page two child panes deep crashes for iPadOS13.1 released version.

**Comment by yvbeek** [comment]
@sashahcat Sorry, I've been very busy with work. I hope to have a look at this in the weekend.

Do you know if this still causes crashes with iPadOS 13.1.2 ?
Does this also crash in the simulator?
Have you found a workaround for this problem?

**Comment by sashahcat** [comment]
Yes, it still crashes with iPadOS 13.1.2. I believe it also crashes in the simulator. No true workaround found. Submitted radar to Apple and waiting, unless someone else finds a workaround. The only workaround I know of would be to reformat to not be two child panes deep, would not display as nicely.

**Comment by sashahcat** [comment]
Seems to have been fixed in iPadOS 13.2. Cheers!
